blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<post_id>[0-9]+)/$', views.view, name='view'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/posts/$', views.user_posts, name='user_posts'),
    url(r'^commentstatus/$', views.change_comment_status, name='change_comment_status'),

    url(r'^comments/$', views.postcomments, name='postcomments'),
    url(r'^new/$', views.newpost, name='new'),
    url(r'^post/edit/(?P<post_id>[0-9]+)/$', views.edit_post, name='edit_post'),

    url(r'^posts/tag/(?P<slug>[\w-]+)$', views.posts_by_tag, name='postsbytag'),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout')
]

djblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blog import views

urlpatterns = [
    url(r'^$', views.index, name='blogindex'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
]

blog/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=50)
    frequency = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Post(models.Model):
    DRAFT = 'draft'
    PUBLISHED = 'published'
    HIDDEN = 'hidden'
    DELETED = 'deleted'
    STATUSES = (
        (DRAFT, 'Draft'),
        (PUBLISHED, 'Published'),
        (HIDDEN, 'Hidden'),
        (DELETED, 'Deleted'),
        )
    title = models.CharField(max_length=50)
    content = models.TextField()
    tags = models.ManyToManyField(Tag)
    status = models.CharField(max_length=50,
                                choices=STATUSES,
                                default=DRAFT)
    created = models.DateTimeField('Date Created',
                                    auto_now_add=True,
                                    blank=True)
    published = models.DateTimeField('Date Published',
                                        auto_now=True)
    owner = models.ForeignKey(User, null=True)

    def __str__(self):
        return self.title

    def get_post_comments_published(self):
        return Comment.objects.filter(
            status__exact='published',
            post__id__exact=self.pk
        ).order_by('-created')[:5]

    def get_post_comments_all(self):
        return Comment.objects.filter(
            post__id__exact=self.pk
        ).order_by('-created')[:5]

class Comment(models.Model):
    PUBLISHED = 'published'
    HIDDEN = 'hidden'
    DELETED = 'deleted'
    STATUSES = (
        (PUBLISHED, 'Published'),
        (HIDDEN, 'Hidden'),
        (DELETED, 'Deleted'),
        )
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    status = models.CharField(max_length=50,
                                choices=STATUSES,
                                default=HIDDEN)
    created = models.DateTimeField('Date Created',
                                        auto_now_add=True,
                                        blank=True)
    name = models.CharField(blank=False,
                            null=False,
                            max_length=50,
                            default='Anonymous')
    email = models.EmailField(null=True, blank=True)
    url = models.URLField(blank=True)
    owner = models.ForeignKey(User, null=True, blank=True)

    def __str__(self):
        return self.content

blog/forms.py
from django import forms
from .models import Comment, Post

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'email', 'content', 'url')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'url': forms.TextInput(attrs={'class': 'form-control'})
        }

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('owner', 'created', 'published')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'tags': forms.SelectMultiple(attrs={
                'class': 'form-control'
                }),
            'status': forms.Select(attrs={'class': 'form-control'}),
        }

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
        ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control'
        }
        ))

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

from .models import Post, Comment
from .forms import CommentForm, PostForm, LoginForm

import json

# Create your views here.
def index(request):
    latest_blog_posts = Post.objects.order_by('-created')[:5]
    return render(request, 'blog/index.html', {'posts': latest_blog_posts})

def view(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = post.get_post_comments_published()

    if request.method == 'POST':
        form = CommentForm(request.POST)

        # validate form
        if form.is_valid():
            obj = form.save(commit=False)
            obj.post = Post.objects.get(pk=post_id)
            obj.save()

    else:
        form = CommentForm()

    return render(request, 'blog/view.html', {
        'post': post,
        'comments': comments,
        'commentform': form
        })

def profile(request):
    current_user = request.user
    return render(request, 'blog/profile.html', {'user': current_user})

def newpost(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            user = request.user

            obj = form.save(commit=False)
            obj.owner = User.objects.get(pk=user.id)
            obj.save()
    else:
        form = PostForm()
    return render(request, 'blog/newpost.html', {
        'postform': form
        })

def edit_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST or None, instance=post)
    success = False
    if form.is_valid():
        form.save()
        success = True

    return render(request, 'blog/edit_post.html', {
        'editform': form,
        'success': success,
        'post_id': post_id
        })

def postcomments(request):
    user = request.user
    posts = Post.objects.filter(owner__id__exact=user.id)
    comments = []
    for post in posts:
        post_comments = post.get_post_comments_all()
        comments.append(post_comments)
    return render(request, 'blog/postcomments.html', {
        'comments': comments,
        'posts': posts
        })

def posts_by_tag(request, slug):
    posts = Post.objects.filter(tags__name__iexact=slug)
    return render(request, 'blog/posts_by_tag.html', {
        'posts': posts,
        'slug': slug
        })

def user_login(request):
    form = LoginForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/blog')
            else:
                return HttpResponse('Your account is not activated')
    else:
        form = LoginForm()
    return render(request, 'blog/login.html', {'loginform': form})

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/blog')

def user_posts(request):
    user = request.user
    posts = Post.objects.filter(owner__id__exact=user.id)
    return render(request, 'blog/user_posts.html', {'posts': posts})

def change_comment_status(request):
    """
    Accept AJAX request
    I have no idea if this is a good practice or not. /facepalm
    """
    ret = json.dumps({'status': '0'})
    if request.method == 'POST':
        comment_id = request.POST.get('comment_id')
        status = request.POST.get('status')
        comment = Comment.objects.get(pk=comment_id)
        comment.status = status
        comment.save()
        ret = json.dumps({'status': '1'})
    return HttpResponse(ret)

blog/templates/blog/edit_post.html
{% load staticfiles %}
{% include 'blog/includes/head.html' %}
{% include 'blog/includes/nav.html' %}

<div class="container">
    <div class="col-sm-8">
        <div class="row">
            <div class="col-sm-12">
                <h1>Edit Post</h1>
            </div>
            <div class="col-sm-12">
                {% if success %}
                    <div class="alert alert-success">
                        <span>
                            Post has been saved. View it <a href="{% url 'blog:view' post_id %}">here</a>.
                        </span>
                    </div>
                {% endif %}
                <form action="" method="post">
                    {% csrf_token %}
                    {{editform.as_p}}
                    <button class="btn btn-primary" type="submit">Save</button>
                </form>
            </div>

        </div>
    </div>
    {% include 'blog/includes/sidebar.html' %}
</div>

{% include 'blog/includes/foot.html' %}

blog/templates/blog/includes/foot.html
{% load staticfiles %}
    <br />
    <footer>
        Footar
    </footer>

    <script src="{% static "blog/js/jquery-1.12.4.min.js" %}"></script>
    <script src="{% static "blog/js/bootstrap.min.js" %}"></script>
    <script src="{% static "blog/js/comment-status.js" %}"></script>
    </body>
</html>

blog/templates/blog/includes/head.html
{% load staticfiles %}
<!doctype html>
<html>
    <head>
        <title>Yas</title>

        <link rel="stylesheet" href="{% static "blog/css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "blog/css/style.css" %}">

    </head>

    <body>

blog/templates/blog/includes/nav.html
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="{% url 'blog:index' %}">Blog</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="#">About</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">

                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'blog:profile' %}">Your Profile</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:user_logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li><a href="{% url 'blog:user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>

blog/templates/blog/includes/sidebar.html
<div class="col-sm-4">
    <div class="row">
        <div class="well">
            <strong>About</strong>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
        </div>
        <hr>
        <div class="well">
            <strong>Tags</strong>
            <ul class="list-inline">
                <li>
                    <a class="label label-info" href="{% url 'blog:postsbytag' 'technology' %}">Tech</a>
                </li>
                <li>
                    <a class="label label-info" href="{% url 'blog:postsbytag' 'lifestyle' %}">Lifestyle</a>
                </li>
            </ul>
        </div>
    </div>
</div>

blog/templates/blog/index.html
{% include 'blog/includes/head.html' %}
{% include 'blog/includes/nav.html' %}

<div class="container">
    <div class="col-sm-8">
        <div class="row">
            <h1>Blog Index</h1>
            {% for post in posts %}
                <div class="col-xs-12">
                    <h2>{{ post.title|title }}</h2>
                    <small>{{post.created}} by {{post.owner}}</small>
                    <p>{{ post.content|truncatechars:100 }}</p>
                    <ul class="list-inline">
                        {% for tag in post.tags.all %}
                            <li>
                                <a
                                    href="{% url 'blog:postsbytag' tag %}"
                                    class="label label-info">
                                    {{tag}}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                    <a href="{% url 'blog:view' post.id %}" class="btn btn-default">
                        Read More...
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    {% include 'blog/includes/sidebar.html' %}
</div>

{% include 'blog/includes/foot.html' %}

blog/templates/blog/login.html
{% load staticfiles %}
{% include 'blog/includes/head.html' %}
{% include 'blog/includes/nav.html' %}

<div class="container">
    <div class="col-sm-8">
        <div class="row">
            <div class="col-sm-12">
                <h1>User Login</h1>
            </div>
            <div class="col-sm-12">
                <form action="" method="post">
                    {% csrf_token %}
                    {{loginform.as_p}}
                    <button class="btn btn-primary">Login</button>
                </form>
            </div>

        </div>
    </div>
    {% include 'blog/includes/sidebar.html' %}
</div>

{% include 'blog/includes/foot.html' %}

blog/templates/blog/newpost.html
{% load staticfiles %}
{% include 'blog/includes/head.html' %}
{% include 'blog/includes/nav.html' %}

<div class="container">
    <div class="col-sm-8">
        <div class="row">
            <div class="col-sm-12">
                <h1>New Post</h1>
            </div>
            <div class="col-sm-12">
                {% if postform %}
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ postform.as_p }}
                        <button class="btn btn-primary" type="submit">
                            Post
                        </button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
    {% include 'blog/includes/sidebar.html' %}
</div>

{% include 'blog/includes/foot.html' %}

blog/templates/blog/postcomments.html
{% load staticfiles %}
{% include 'blog/includes/head.html' %}
{% include 'blog/includes/nav.html' %}

<div class="container">
    <div class="col-sm-8">
        <div class="row">
            <div class="col-sm-12">
                <h1>Comments on Your Posts</h1>
            </div>
            <div class="col-sm-12">
                <div
                    class="panel-group"
                    id="commentaccordion"
                    role="tablist"
                    aria-multiselectable="true">
                    {% for comment_cluster in comments %}
                        {% for comment in comment_cluster %}
                            <div
                                class="panel panel-default comment-{{comment.status}}">
                                <div
                                    class="panel-heading comment-heading"
                                    role="tab"
                                    id="heading_{{comment.id}}">
                                    <a
                                        role="button"
                                        data-toggle="collapse"
                                        data-parent="#commentaccordion"
                                        href="#collapse_{{comment.id}}"
                                        aria-expanded="true"
                                        aria-controls="collapse_{{comment.id}}">
                                        <strong>{{comment.name}}</strong> commented on <em>{{comment.post}}</em>
                                    </a>
                                </div>
                                <div
                                    id="collapse_{{comment.id}}"
                                    class="panel-collapse collapse"
                                    role="tabpanel"
                                    aria-labelledby="heading_{{comment.id}}">
                                    <div class="panel-body">
                                        <small>
                                            {{comment.created}} -
                                            {{comment.status|upper}}
                                        </small>
                                        <p>
                                            {{comment.name}}'s EMAIL: {{comment.email}}
                                        </p>
                                        <p>
                                            {{comment.name}}'s URL: {{comment.url}}
                                        </p>
                                        <span><strong>Comment:</strong></span>
                                        <p>{{comment}}</p>
                                        <hr>
                                        <span>Comment Status</span><br />
                                        <div
                                            class="btn-group"
                                            role="group"
                                            aria-label="comment_status">
                                            <input
                                                type="hidden"
                                                value="{% url 'blog:change_comment_status' %}"
                                                id="comment_status_{{comment.id}}">
                                            <input
                                                type="hidden"
                                                name="csrfmiddlewaretoken"
                                                value="{{ csrf_token }}"
                                                id="comment_csrf_{{comment.id}}">

                                            <button
                                                type="button"
                                                data-stype="hidden"
                                                data-cid="{{comment.id}}"
                                                class="btn comment-action btn-default">
                                                Hidden
                                            </button>
                                            <button
                                                type="button"
                                                data-stype="published"
                                                data-cid="{{comment.id}}"
                                                class="btn comment-action btn-success">
                                                Published
                                            </button>
                                            <button
                                                type="button"
                                                data-stype="deleted"
                                                data-cid="{{comment.id}}"
                                                class="btn comment-action btn-danger">
                                                Deleted
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% include 'blog/includes/sidebar.html' %}
</div>

{% include 'blog/includes/foot.html' %}

blog/templates/blog/posts_by_tag.html
{% load staticfiles %}
{% include 'blog/includes/head.html' %}
{% include 'blog/includes/nav.html' %}

<div class="container">
    <div class="col-sm-8">
        <div class="row">
            <div class="col-sm-12">
                <h1>Posts with tag <strong>{{slug}}</strong></h1>
            </div>
            {% for post in posts %}
                <div class="col-sm-12">
                    <h2>{{post.title}}</h2>
                    <p>{{post.content|truncatewords:50}}</p>
                    <span>
                        <a class="btn btn-info" href="{% url 'blog:view' post.id %}">View Post</a>
                    </span>
                </div>
            {% endfor %}
        </div>
    </div>
    {% include 'blog/includes/sidebar.html' %}
</div>

{% include 'blog/includes/foot.html' %}

blog/templates/blog/profile.html
{% load staticfiles %}
{% include 'blog/includes/head.html' %}
{% include 'blog/includes/nav.html' %}
<div class="container">

    {% if user %}
        <div class="col-sm-8">

            <div class="row">
                <div class="col-sm-12">
                    <ul class="nav nav-pills">
                        <li role="presentation" class="active">
                            <a href="{% url 'blog:profile' %}">Profile</a>
                        </li>
                        <li role="presentation">
                            <a href="{% url 'blog:new' %}">New Post</a>
                        </li>
                        <li role="presentation">
                            <a href="{% url 'blog:postcomments' %}">Mod Comments</a>
                        </li>
                        <li role="presentation">
                            <a href="{% url 'blog:user_posts' %}">Your Posts</a>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-12">
                    <h1>User Profile</h1>
                </div>

                <div class="col-sm-2 col-md-2">
                    <a href="#" class="thumbnail">
                        <img
                            src="{% static "blog/img/9.jpg" %}"
                            alt="thumbnail"
                            class="img-responsive">
                    </a>
                </div>
                <div class="col-sm-4 col-md-4">
                    <blockquote>
                        <p>{{ user.first_name }} {{ user.last_name }}</p> <small><cite title="Source Title">Gotham, United Kingdom  <i class="glyphicon glyphicon-map-marker"></i></cite></small>
                    </blockquote>
                    <p>
                        <i class="glyphicon glyphicon-envelope"></i> {{ user.email }}
                    </p>
                </div>


            </div>
        </div>
    {% else %}
        <div class="col-sm-8">
            <div class="row">
                <div class="alert alert-danger">An error occured.</div>
            </div>
        </div>
    {% endif %}

    {% include 'blog/includes/sidebar.html' %}
</div>

{% include 'blog/includes/foot.html' %}

blog/templates/blog/user_posts.html
{% load staticfiles %}
{% include 'blog/includes/head.html' %}
{% include 'blog/includes/nav.html' %}

<div class="container">
    <div class="col-sm-8">
        <div class="row">
            <div class="col-sm-12">
                <h1>Your Posts</h1>
            </div>
            <div class="col-sm-12">
                {% for post in posts %}
                    <div class="col-md-10 user-post">
                        <h1>{{post.title}}</h1>
                        <img src="{% static "blog/img/3.png" %}" alt="post img" class="pull-left img-responsive thumb">

                        <em>
                            <small>posted: {{post.created}}&nbsp;</small>
                            <small>
                                author: <strong>{{post.owner}}&nbsp;</strong>
                            </small>
                            <small class="label label-default">{{post.status}}</small>
                        </em>
                        <article>
                            <p>
                                {{post.content|truncatewords:50}}
                            </p>
                         </article>
                        <a
                            class="btn btn-primary pull-right"
                            href="{% url 'blog:edit_post' post.id %}">
                            EDIT POST
                        </a>
                        <a
                            class="btn btn-primary pull-right"
                            href="{% url 'blog:view' post.id %}">
                            READ MORE
                        </a>
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>
    {% include 'blog/includes/sidebar.html' %}
</div>

{% include 'blog/includes/foot.html' %}

blog/templates/blog/view.html
{% load staticfiles %}
{% include 'blog/includes/head.html' %}
{% include 'blog/includes/nav.html' %}

<div class="container">
    <div class="col-sm-8">
        <div class="row">
            {% if post %}
                <h1>{{ post.title }}</h1>
                <p>
                    <span>
                    {{ post.created|date:"M d, Y h:ia" }} by
                    {{ post.owner }}
                    </span>
                </p>
                {% autoescape on %}
                    {{ post.content|linebreaksbr }}
                {% endautoescape %}
                <hr>
                Tags:
                <ul class="list-inline">
                    {% for tag in post.tags.all %}
                        <li>
                            <span class="label label-info">
                                {{ tag.name }}
                            </span>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="row">
            <h2>Leave a Comment</h2>
            <form action="" method="post">
                {% csrf_token %}
                {{ commentform.as_p }}
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
        <div class="row">
            <h2>Comments</h2>
            {% if comments %}
                {% for comment in comments %}
                    <div class="row">
                        <div class="col-sm-2">
                            <a href="#" class="thumbnail">
                                <img
                                    src="{% static "blog/img/9.jpg" %}"
                                    alt="thumbnail">
                            </a>
                        </div>
                        <div class="col-sm-10">
                            {% if comment.name %}
                                <p>
                                    <strong>{{ comment.name }}</strong>
                                    <small>
                                        {{comment.created}}
                                    </small>
                                </p>
                            {% else %}
                                <p><strong>Anonymous</strong></p>
                            {% endif %}
                            {{ comment.content|linebreaksbr }}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="alert alert-info">
                    <p>There are no comments posted yet.</p>
                </div>
            {% endif %}
        </div>
    </div>
    {% include 'blog/includes/sidebar.html' %}
</div>

{% include 'blog/includes/foot.html' %}